version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pipo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pipo
      POSTGRES_PASSWORD: pipo123
      POSTGRES_DB: pipo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipo-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Windows & Linux için erişim kolaylığı

  pgadmin:
    image: dpage/pgadmin4
    container_name: pipo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pipo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pipo-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
    name: pipo-postgres-data

networks:
  pipo-network:
    name: pipo-network
